# Build stage
FROM node:20-alpine AS builder
WORKDIR /app

# Install deps
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

# Copy source and build at runtime
COPY . .

CMD ["/bin/sh", "-c", "rm -rf dist/* && npm run build && ls -laR dist"]
