services:
  client:
    container_name: redtetris-client
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: >-
      sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"

volumes:
  client_node_modules:
