services:
  client:
    container_name: redtetris-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

  server:
    container_name: redtetris-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  caddy:
    container_name: redtetris-caddy-dev
    attach: false
    image: caddy:2.10
    depends_on:
      - client
      - server
    ports:
      - "4242:80"
      - "4243:443"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro  # Using Caddyfile.dev

volumes:
  client_node_modules:
  server_node_modules:
