services:
  client:
    container_name: redtetris-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DOMAIN_NAME=$DOMAIN_NAME
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    networks:
      - reverse-proxy

  server:
    container_name: redtetris-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DOMAIN_NAME=$DOMAIN_NAME
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    networks:
      - reverse-proxy

  caddy:
    container_name: redtetris-caddy-dev
    attach: false
    image: caddy:2.10
    depends_on:
      - client
      - server
    ports:
      # - "80:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro  # Using Caddyfile.dev
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    networks:
      - reverse-proxy

volumes:
  client_node_modules:
  server_node_modules:

networks:
  reverse-proxy:
