services:
  client:
    container_name: redtetris-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/dist:/app/dist
    networks:
      - redtetris-net
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME

  server:
    container_name: redtetris-server-prod
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      client:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=production
      - DOMAIN_NAME=$DOMAIN_NAME
    ports:
      - "8080:80"
    volumes:
      - ./client/dist:/app/client:ro
    networks:
      - redtetris-net

volumes:
  redtetris-dist:

networks:
  redtetris-net:
