FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=development

# Expose server port
EXPOSE 3000

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

CMD ["sh", "-c", "node --watch src/main.js"]


